name: islamy_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_compass: ^0.7.0
  flutter_localizations:
    sdk: flutter
  http: ^0.13.4
  flutter_spinkit: ^5.1.0
  carousel_slider: ^4.0.0
  share_plus: ^4.0.3
  clipboard: ^0.1.3
  audioplayers: ^0.20.1
  shared_preferences: 2.0.15
  smooth_page_indicator: ^1.0.0+2
  flutter_launcher_icons: ^0.9.2
  intl: ^0.17.0
  flutter_qiblah: ^2.0.2
  geolocator: ^7.7.1
  adhan:  ^2.0.0-nullsafety.2
  flutter_svg: ^1.1.0

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/qua.png"

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/json/
    - assets/ca/

  fonts:
    - family: RobotoSerif
      fonts:
        - asset: assets/fonts/RobotoSerif_72pt_SemiExpanded-Regular.ttf
          weight: 700
